Add bridge
openprocurement/openprocurement.bot.identification pull request #10
Opened 2017-03-24 16:54 UTC by Krokop

2017-03-27 07:14 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-27 10:12 UTC, kroman0 requested changes
bridge лише один тест і покриття лише 46%

2017-03-29 05:59 UTC, Krokop commented
@kroman0 покрив bridge на 90%, потрібен ревью

2017-03-29 09:00 UTC, kroman0 requested changes

2017-03-29 09:00 UTC, kroman0 commented on .coveragerc
> +        urllib3.contrib.pyopenssl.inject_into_urllib3()
Приберіть всі такі фікси, так як requests = 2.10.0 (https://github.com/openprocurement/openprocurement.bridge.buildout/blob/edr_integration/profiles/versions.cfg#L161) має виправлення.

2017-03-29 10:22 UTC, Krokop commented
@kroman0 зробив merge з master та прибрав urllib3.contrib.pyopenssl.inject_into_urllib3(). Потрібен ревью

2017-03-29 10:34 UTC, kroman0 approved these changes

2017-03-29 10:37 UTC, merged