Add filter_tender worker + tests.
openprocurement/openprocurement.bot.identification pull request #4
Opened 2017-03-15 08:03 UTC by Krokop

2017-03-15 10:52 UTC, kroman0 requested changes

2017-03-15 10:52 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +                elif 'bids' in tender:
bids? Напевно qualifications?

2017-03-15 10:52 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Тут потрібно додати обробку того що черга пуста

2017-03-15 10:52 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +                if 'awards' in tender:
Доцільніше поміняти місцями перевірку awards і qualifications. Довідки в процедурах з прекваліфікацією не потрібно дублювати в посткваліфікації.

2017-03-15 11:18 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
якщо черга пуста, gevent переключе виконання на наступний greenlet

2017-03-15 11:21 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +                if 'awards' in tender:
Згоден, але згідно ТЗ потрібно робити в 2 місцях
https://docs.google.com/document/d/1Bl_tiN1TdbreII6koSCGcv5ZT7rtZrGPidRMdqP_50U/edit#heading=h.gj495yxz3chz

2017-03-15 11:45 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +                elif 'bids' in tender:
qualifications - буде краще

2017-03-15 12:55 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Спробував відтворити і мені віддавався LoopExit. В такому випадку prepare_data буде ламатись, а _run буде відновлювати prepare_data.

2017-03-15 13:12 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
При queue.peek() викликається self.hub.switch(), якщо не буде інших greenlests то повернеться LoopExit. В нашому випадку ми маємо більше 1 greenlet то виконання передасться в _run. Або я щось упустив?

2017-03-15 16:01 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Так. Але у випадку якщо інших greenlets не залишиться все ж буде exception. Доцільніше обробляти що черга пуста і не допускати вмирання greenlet. Наступний може запуститись лише за self.delay секунд.

2017-03-16 09:11 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
_run теж вважається greenlet, тому exception LoopExit виникне тільки коли помруть всі, якщо всі померли то не потрібно залишати зомбі воркер.

2017-03-16 13:31 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
greenlet повинен коректно завершуватись.
https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/211315999#L200
https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/211315999#L208
https://travis-ci.org/openprocurement/openprocurement.bot.identification/builds/211315999#L216

2017-03-16 13:41 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Ми тестуємо непередбачуваний збій в роботі, тому exceptions вилітають в логи.

2017-03-16 13:42 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Також тестуємо чи відновиться робота після

2017-03-20 14:27 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Вважаю доцільнішим коректний вихід а не exception. В даному випадку можна додати timeout для отримання з черги і перевірку того що отримане. Також в місцях де є while True можна додати умову виходу як https://github.com/openprocurement/openprocurement.edge/blob/master/openprocurement/edge/workers.py#L263 . Це дозволить також спростити тестування даного коду(можна встановлювати коли завершиться вічний цикл)

2017-03-21 09:23 UTC, Krokop commented
@kroman0 приклад дивної поведінки coverage, при зміни 1 строки покриття впало на 2%.

2017-03-21 10:38 UTC, kroman0 commented on .coveragerc
> +    *openprocurement/bot/identification/__init__.py
Потрібно забрати https://github.com/openprocurement/openprocurement.bot.identification/blob/master/openprocurement/bot/identification/__init__.py#L4 і далі щоб не додавати цього рядка

2017-03-21 12:03 UTC, Krokop commented on .coveragerc
> +    *openprocurement/bot/identification/__init__.py
Done

2017-03-21 12:57 UTC, kroman0 commented on .coveragerc
> +    *openprocurement/bot/identification/__init__.py
Поверніть openprocurement/bot/__init__.py а openprocurement/bot/identification/__init__.py залиште порожнім. openprocurement/bot/__init__.py потрібен для визначення namespace а порожнього openprocurement/bot/identification/__init__.py досить для визначення модуля.

2017-03-21 14:21 UTC, kroman0 commented
https://github.com/openprocurement/openprocurement.bot.identification/pull/4#discussion_r106913884

2017-03-22 08:42 UTC, Krokop commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Замінив while True на while not self.exit.
З приводу решти коментарря не дуже зрозуміло, що саме потрібно змінити.

2017-03-22 10:18 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Писав про queue.peek() щоб не допускати появи exception(якщо код справді працює як передбачено).

2017-03-22 10:22 UTC, kroman0 commented on openprocurement/bot/identification/databridge/filter_tender.py
> +            tender_id = self.filtered_tender_ids_queue.peek()
Виніс це в #7

2017-03-22 10:22 UTC, kroman0 approved these changes

2017-03-22 10:23 UTC, merged