Унікальний внутрішній ідентифікатор довідки
openprocurement/openprocurement.bot.identification pull request #47
Opened 2017-05-13 12:26 UTC by IrynaPomazan

[issue](https://github.com/openprocurement/openprocurement.bot.identification/issues/32)

2017-05-15 08:18 UTC, kroman0 requested changes

2017-05-15 08:18 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +    error_details = {'data': {'error': 'Couldn\'t find this code in EDR.'}}
Це видалялось в #45

2017-05-15 08:18 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
```При формуванні довідки потрібно генерувати унікальний ідентифікатор довідки в момент визначення потреби в її формуванні```
Тут унікальний ідентифікатор довідки генерується в момент запиту до проксі.

2017-05-15 08:34 UTC, IrynaPomazan commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
Мається на увазі формування унікального ідентифікатору в момент коли ми виявили, що данний tender/qualification/award в необхідному статусі та не мають документ з типом 'registerExtract' (в коді це файл filter_tender.py)?

2017-05-15 09:40 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
Так

2017-05-15 10:20 UTC, IrynaPomazan commented
Є проблема в даній реалізації, що робити коли ЄДР API повертає у відповідь  два об'єкти на 1 ЄДРПОУ код і потрібно завантажити 2 два файли?

2017-05-15 11:04 UTC, IrynaPomazan commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
Є проблема в даній реалізації, що робити коли ЄДР API повертає у відповідь два об'єкти на 1 ЄДРПОУ код і потрібно завантажити 2 два файли?

2017-05-15 11:33 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
Це не проблема. В такому випадку, коли є більше 1 довідки, довідки мали б отримати суфікс з номером довідки для ідентифікації, що ЄДР має два записи по 1 ЄДРПОУ коду. Доцільно використати запис n з m, щоб було зрозуміло скільки довідок має бути. Наприклад, `id.m.n`

2017-05-15 11:39 UTC, IrynaPomazan commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                document_id = generate_doc_id()
Ок, перероблюємо

2017-05-16 08:38 UTC, kroman0 approved these changes

2017-05-16 08:38 UTC, merged