Add upload
openprocurement/openprocurement.bot.identification pull request #8
Opened 2017-03-22 12:41 UTC by Krokop

2017-03-22 13:26 UTC, kroman0 requested changes

2017-03-22 13:26 UTC, kroman0 commented on openprocurement/bot/identification/client.py
> +        self.headers = {"Authorization": "Basic {token}".format(token=self.token)}
Для аутентифікації Document Service використовується Basic Authenication схема
http://docs.python-requests.org/en/master/user/authentication/#basic-authentication
http://documentservice.api-docs.openprocurement.org/en/latest/authentication.html

2017-03-22 13:26 UTC, kroman0 commented on openprocurement/bot/identification/databridge/upload_file.py
> +from gevent import monkey
Для чого ви додаєте `from gevent import monkey; monkey.patch_all()` в цьому модулі?

2017-03-22 13:26 UTC, kroman0 commented on openprocurement/bot/identification/client.py
> +        files = {'file': files}
Для того щоб був коректний content type краще files формувати як https://github.com/openprocurement/openprocurement.api/blob/master/src/openprocurement/api/utils.py#L139

2017-03-22 13:26 UTC, kroman0 commented on openprocurement/bot/identification/tests/upload_file.py
> +                                    'format': 'text/plain',
Некоректні title і format

2017-03-22 15:50 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-23 15:10 UTC, kroman0 requested changes

2017-03-23 15:10 UTC, kroman0 commented on openprocurement/bot/identification/databridge/utils.py
> +    temporary_file.write(json.dumps(details, indent=4, separators=(',', ': '), ensure_ascii=False).encode('utf-8'))
Файл виписки повинен бути yaml

2017-03-23 15:29 UTC, Krokop commented on openprocurement/bot/identification/databridge/utils.py
> +    temporary_file.write(json.dumps(details, indent=4, separators=(',', ': '), ensure_ascii=False).encode('utf-8'))
В ТЗ 

> Файл у форматі json, тип файлу - yaml

Чому саме yaml?

2017-03-23 15:53 UTC, kroman0 commented on openprocurement/bot/identification/databridge/utils.py
> +    temporary_file.write(json.dumps(details, indent=4, separators=(',', ': '), ensure_ascii=False).encode('utf-8'))
В системи вже використовуються audit.yaml з модуля аукціонів. Чому саме так написано в ТЗ не можу сказати. В теорії бібліотека yaml вміє читати json. Якщо не передавати indent для json, то yaml більш читабельний. Якщо це питання критичне то можемо уточнити який формат потрібен?

2017-03-24 10:29 UTC, Krokop commented on openprocurement/bot/identification/databridge/utils.py
> +    temporary_file.write(json.dumps(details, indent=4, separators=(',', ': '), ensure_ascii=False).encode('utf-8'))
Переробили на yaml

2017-03-24 10:35 UTC, Krokop commented
@kroman0 Потрібен ревью

2017-03-24 11:16 UTC, kroman0 approved these changes

2017-03-24 11:16 UTC, merged