fix json decode error
openprocurement/openprocurement.bot.identification pull request #86
Opened 2017-06-26 13:01 UTC by gorserg

Помилка виникала при спробі парсингу тіла помилки, яку повернув ЄДР API. Такі випадки тепер коректно логуються, а сам елемент переміщається у кінець відповідної черги.
issue #78

2017-06-27 06:32 UTC, itvan commented
@kroman0 please, review

2017-07-03 08:15 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                            data_string(tender_data), document_id, re.args[1].json().get('errors')),
В випадку коли відповідь не json можна записати в журнал текст відповіді(re.args[1].text)

2017-07-03 11:46 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        error_response = re.args[1].json().get('errors') if isinstance(re.args[1].json(), dict) else re.args[1].text
В випадку коли відповідь не json всеодно буде exception(на re.args[1].json()). Можна саме цей рядок витягнути в try/except і при попаданні в except `error_response = re.args[1].text`

2017-07-03 14:15 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                            data_string(tender_data), document_id, re.args[1].json()),
Поверніть попередній код де визначався error_response і його вдягніть в error_response = re.args[1].text і тільки його.

2017-07-03 14:27 UTC, gorserg commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                            data_string(tender_data), document_id, re.args[1].json()),
тобто взагалі не робити re.args[1].json() в будь-якому випадку ? тоді просто у змінній error_response немає змісту

2017-07-03 14:45 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                            data_string(tender_data), document_id, re.args[1].json()),
проблема втому щоб не міняти logger.info але замість re.args[1].json() використати підготовлений error_response(якщо в відповіді не json то re.args[1].text, якщо json тоді re.args[1].json())
Також вартує поправити handle_status_response щоб не ламалось на ```response.json().get('errors')[0].get('description')```

2017-07-03 16:06 UTC, kroman0 requested changes

2017-07-03 16:06 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        self.handle_status_response(re.args[1], tender_data.tender_id)
Винесіть self.handle_status_response з try

2017-07-03 16:06 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        logger.exception("Exception could not be parsed into json")
Цього не потрібно

2017-07-03 16:29 UTC, gorserg commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        self.handle_status_response(re.args[1], tender_data.tender_id)
Якщо винести - залишиться ймовірність падіння у handle_status_response (там дуже малоймовірно, умову посилили через перевірку content-type, але все ж). Якщо ми його не піймаємо - це критично, так як не буде перекладено елемент в кінець черги (self.retry_edr_ids_queue.put(self.retry_edr_ids_queue.get())).
Те що зараз handle_status_response у блоці try гарантує коректне виведення info з re.args[1].text, єдине що ми так можемо втратити - це вивід у лог logger.warning (той що всередині handle_status_response), але для діагностики проблеми info цілком достаньо. 
Якщо все ж потрібно винести - то тоді треба всередині handle_status_response  робити схожу логіку з try - але це вже дублювання коду наче.

2017-07-03 16:30 UTC, gorserg commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        logger.exception("Exception could not be parsed into json")
Добавлено з метою сигналізувати, що отримано неочікувану відповідь від ЄДР (на info в логах можна і не звернути увагу, тут наче саме б exception потрібно - так як неочікувана поведінка). Приберемо раз все ж надлишкова інформація.

2017-07-04 08:32 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        logger.exception("Exception could not be parsed into json")
Це може бути цілком очікувана поведінка.

2017-07-04 08:36 UTC, kroman0 commented on openprocurement/bot/identification/databridge/edr_handler.py
> +                        self.handle_status_response(re.args[1], tender_data.tender_id)
Якщо ви вважаєте що в handle_status_response недостатньо перевірки щоб не виліз exception тоді можете залишити.

2017-07-04 08:44 UTC, kroman0 approved these changes

2017-07-04 08:45 UTC, merged